import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { APP_CONFIG } from "../utils/appConfig";
import { trpc } from "../utils/trpc";

export default function Home() {
  const { data, isLoading } = trpc.hello.useQuery({ text: "Kyle" });

  if (isLoading) return <div>Loading</div>;

  return (
    <div className={styles.container}>
      <Head>
        <title>{APP_CONFIG.APP_TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="font-bold text-2xl">{data?.greeting}</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {APP_CONFIG.COMPANY_NAME}
        </a>
      </footer>
    </div>
  );
}
